
<!DOCTYPE html>
<!--[if IEMobile 7 ]><html class="no-js iem7"><![endif]-->
<!--[if lt IE 9]><html class="no-js lte-ie8"><![endif]-->
<!--[if (gt IE 8)|(gt IEMobile 7)|!(IEMobile)|!(IE)]><!--><html class="no-js" lang="en"><!--<![endif]-->
<head>
  <meta charset="utf-8">
  <title>twitter-python BadStatusLine错误 - xixitalk's snippet</title>
  <meta name="author" content="xixitalk">

  
  <meta name="description" content="事情是这样的：我用twitter-python在本地运行， 抓取一个推号的homeline， 抓取后sleep两分钟再抓取， 不停的循环｡从昨天早上开始， 程序出现如下错误， 且每次都是这个错误｡获得推友收藏列表和fo人的api返回都是正常的，就是REST的api出这种错误。 1
2
3
4
5 &hellip;">
  

  <!-- http://t.co/dKP3o1e -->
  <meta name="HandheldFriendly" content="True">
  <meta name="MobileOptimized" content="320">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  
  <link rel="canonical" href="http://xixitalk.github.io/blog/2014/04/06/twitter-python-badstatusline">
  <link href="/favicon.png" rel="icon">
  <link href="/stylesheets/screen.css" media="screen, projection" rel="stylesheet" type="text/css">
  
  <script src="/javascripts/modernizr-2.0.js"></script>
  <script src="/javascripts/ender.js"></script>
  <script src="/javascripts/octopress.js" type="text/javascript"></script>
  <link href="/atom.xml" rel="alternate" title="xixitalk's snippet" type="application/atom+xml">
  <!--Fonts from Google"s Web font directory at http://google.com/webfonts -->
<link href="http://fonts.googleapis.com/css?family=PT+Serif:regular,italic,bold,bolditalic" rel="stylesheet" type="text/css">
  
  <script type="text/javascript">
    var _gaq = _gaq || [];
    _gaq.push(['_setAccount', 'UA-32324744-1']);
    _gaq.push(['_trackPageview']);

    (function() {
      var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
      ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
      var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
    })();
  </script>



</head>

<body   >
  <header role="banner"><hgroup>
  <h1><a href="/">xixitalk's snippet</a></h1>
  
    <h2>Post Longer Than 140 Characters Tweets</h2>
  
</hgroup>

</header>
  <nav role="navigation"><ul class="subscription" data-subscription="rss">
  <li><a href="/atom.xml" rel="subscribe-rss" title="subscribe via RSS">RSS</a></li>
  
</ul>
  
<form action="http://google.com/search" method="get">
  <fieldset role="search">
    <input type="hidden" name="q" value="site:xixitalk.github.io" />
    <input class="search" type="text" name="q" results="0" placeholder="Search"/>
  </fieldset>
</form>
  
<ul class="main-navigation">
  <li><a href="/">Blog</a></li>
  <li><a href="/blog/archives">Archives</a></li>
  <li><a href="/blog/categories/">Categories</a></li>
  <li><a href="/wishlist/">My wishlist</a></li>
  <li><a href="/about/">About me</a></li>
</ul>

</nav>
  <div id="main">
    <div id="content">
      <div>
<article class="hentry" role="article">
  
  <header>
    
      <h1 class="entry-title">twitter-python BadStatusLine错误</h1>
    
    
      <p class="meta">
        








  


<time datetime="2014-04-06T20:20:25+00:00" pubdate data-updated="true">Apr 6<span>th</span>, 2014</time>
        
         | <a href="#disqus_thread">Comments</a>
        
      </p>
    
  </header>


<div class="entry-content"><p>事情是这样的：我用<a href="https://github.com/bear/python-twitter">twitter-python</a>在本地运行， 抓取一个推号的homeline， 抓取后sleep两分钟再抓取， 不停的循环｡从昨天早上开始， 程序出现如下错误， 且每次都是这个错误｡获得推友收藏列表和fo人的api返回都是正常的，就是REST的api出这种错误。</p>

<!--more-->

<div class="bogus-wrapper"><notextile><figure class="code"><div class="highlight"><table><tr><td class="gutter"><pre class="line-numbers"><span class="line-number">1</span>
<span class="line-number">2</span>
<span class="line-number">3</span>
<span class="line-number">4</span>
<span class="line-number">5</span>
<span class="line-number">6</span>
<span class="line-number">7</span>
<span class="line-number">8</span>
<span class="line-number">9</span>
<span class="line-number">10</span>
<span class="line-number">11</span>
<span class="line-number">12</span>
<span class="line-number">13</span>
<span class="line-number">14</span>
<span class="line-number">15</span>
<span class="line-number">16</span>
<span class="line-number">17</span>
<span class="line-number">18</span>
<span class="line-number">19</span>
<span class="line-number">20</span>
</pre></td><td class="code"><pre><code class=""><span class="line">Traceback (most recent call last):
</span><span class="line">  File "hottweetdo.py", line 183, in &lt;module&gt;
</span><span class="line">    main()
</span><span class="line">  File "hottweetdo.py", line 126, in main
</span><span class="line">    status = api2.GetHomeTimeline(since_id=since_id1,count=200)
</span><span class="line">  File "/media/westdata/read/python-twitter-master/twitter/api.py", line 541, in GetHomeTimeline
</span><span class="line">    json = self._RequestUrl(url, 'GET', data=parameters)
</span><span class="line">  File "/media/westdata/read/python-twitter-master/twitter/api.py", line 3383, in _RequestUrl
</span><span class="line">    timeout=self._requests_timeout
</span><span class="line">  File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 55, in get
</span><span class="line">    return request('get', url, **kwargs)
</span><span class="line">  File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 44, in request
</span><span class="line">    return session.request(method=method, url=url, **kwargs)
</span><span class="line">  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 383, in request
</span><span class="line">    resp = self.send(prep, **send_kwargs)
</span><span class="line">  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 486, in send
</span><span class="line">    r = adapter.send(request, **kwargs)
</span><span class="line">  File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 382, in send
</span><span class="line">    raise ConnectionError(e)
</span><span class="line">requests.exceptions.ConnectionError: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /1.1/statuses/home_timeline.json?count=200 (Caused by &lt;class 'httplib.BadStatusLine'&gt;: '')
</span></code></pre></td></tr></table></div></figure></notextile></div>

<p>代码很简单，就是用四个key生成一个api对象，然后直接调用<code>GetHomeTimeline</code></p>

<p>我google之后， 看到很多类似的分析， 但是我都尝试了， 还是没有解决｡尝试罗列如下｡</p>

<h3 id="bad-proxy-server">bad proxy server</h3>
<p><a href="https://stackoverflow.com/questions/18478013/python-requests-exceptions-connectionerror-max-retries-exceeded-witth-url">有人说是bad proxy server</a>,程序确实使用代理了，代理是shadowsocks+polipo， 代理设置在环境变量HTTP_PROXY和HTTPS_PROXY｡我尝试了不同地区的代理， 甚至切换了不同卖家的代理， 依然出错｡</p>

<h3 id="dns">DNS问题</h3>
<p>尝试了不同的DNS server不起作用</p>

<h3 id="httplib2-08-077">httplib2 0.8的问题， 使用0.7.7</h3>
<p>不起作用</p>

<h3 id="twitter-api">twitter API的问题</h3>
<p>twitter-python的一个<a href="https://github.com/bear/python-twitter/issues/131">issues解答</a>说是twitter API诡异的问题｡问题是我只能等待吗？</p>

<h3 id="maxretries5">设置maxretries为5</h3>
<p><a href="https://stackoverflow.com/questions/15431044/can-i-set-max-retries-for-requests-request/15431343#15431343">https://stackoverflow.com/questions/15431044/can-i-set-max-retries-for-requests-request/15431343#15431343</a> 不起作用</p>

<h3 id="requestssession-keep-alivefalse">设置requests的session keep-alive为False</h3>
<p>不起作用</p>

<p>请python高手或者twitter api高手指点迷津，可以直接在下面留言，或者推上@我。</p>

<h2 id="section">[更新后记]</h2>

<p>目前解决的办法：1、重新新建一个API，用新的consumer_key和access token；2、更换代理，换用tor+polipo，tor的IP变化比较频繁。经过上面操作，错误暂时不再出现了。</p>

<p>问题可能原因：应该是twitter服务器认为API滥用了，当get提交给服务器后，twitter服务器只返回了ACK，接下来没有返回任何数据，所以httplib判断为BadStatusLine，因为没有数据，所以连status号都没有。</p>

<h2 id="section-1">[再次更新后记]</h2>
<p>每天生成HTMLpush到github后自动发推又出现BadStatusLine了，所幸不是<code>GetHomeTimeline</code>。</p>

<div class="bogus-wrapper"><notextile><figure class="code"><div class="highlight"><table><tr><td class="gutter"><pre class="line-numbers"><span class="line-number">1</span>
</pre></td><td class="code"><pre><code class=""><span class="line">requests.exceptions.ConnectionError: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /1.1/statuses/update.json (Caused by &lt;class 'httplib.BadStatusLine'&gt;: '')
</span></code></pre></td></tr></table></div></figure></notextile></div>
</div>


  <footer>
    <p class="meta">
      
  

<span class="byline author vcard">Posted by <span class="fn">xixitalk</span></span>

      








  


<time datetime="2014-04-06T20:20:25+00:00" pubdate data-updated="true">Apr 6<span>th</span>, 2014</time>
      

<span class="categories">
  
    <a class='category' href='/blog/categories/tech/'>tech</a>
  
</span>


    </p>
    
      <div class="sharing">
  
  
  
  
   share to: <a href="http://twitter.com/home?status=Blog:twitter-python BadStatusLine错误 http://xixitalk.github.io/blog/2014/04/06/twitter-python-badstatusline/" target="_blank"><img src="/images/tweet.png" /></a>
  

</div>

    



</footer>
</article>

  <section>
    <h1>Comments</h1>
    <div id="disqus_thread" aria-live="polite"><noscript>Please enable JavaScript to view the <a href="http://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
</div>
  </section>

</div>

<aside class="sidebar">
  
    <section>
  <h1>Categories</h1>
    <ul id="category-list"><li><a href='/blog/categories/android'>android (2)</a></li><li><a href='/blog/categories/apple'>apple (1)</a></li><li><a href='/blog/categories/art'>art (2)</a></li><li><a href='/blog/categories/base64'>base64 (1)</a></li><li><a href='/blog/categories/book'>book (1)</a></li><li><a href='/blog/categories/bugfix'>bugfix (3)</a></li><li><a href='/blog/categories/bullshit'>bullshit (1)</a></li><li><a href='/blog/categories/censor'>censor (1)</a></li><li><a href='/blog/categories/cowproxy'>cowproxy (1)</a></li><li><a href='/blog/categories/cryptography'>cryptography (1)</a></li><li><a href='/blog/categories/ddns'>DDNS (1)</a></li><li><a href='/blog/categories/dnsmasq'>dnsmasq (1)</a></li><li><a href='/blog/categories/english'>english (1)</a></li><li><a href='/blog/categories/flashfire'>flashfire (1)</a></li><li><a href='/blog/categories/flask-twip'>flask_twip (2)</a></li><li><a href='/blog/categories/flickr'>flickr (1)</a></li><li><a href='/blog/categories/foursquare'>foursquare (1)</a></li><li><a href='/blog/categories/funny'>funny (1)</a></li><li><a href='/blog/categories/git'>git (4)</a></li><li><a href='/blog/categories/github'>github (1)</a></li><li><a href='/blog/categories/golang'>golang (2)</a></li><li><a href='/blog/categories/heroku'>heroku (1)</a></li><li><a href='/blog/categories/hpv'>HPV (1)</a></li><li><a href='/blog/categories/iptables'>iptables (1)</a></li><li><a href='/blog/categories/kernel'>kernel (4)</a></li><li><a href='/blog/categories/libc'>libc (2)</a></li><li><a href='/blog/categories/life'>life (14)</a></li><li><a href='/blog/categories/linux'>linux (16)</a></li><li><a href='/blog/categories/markdown'>markdown (1)</a></li><li><a href='/blog/categories/math'>math (1)</a></li><li><a href='/blog/categories/mathjax'>mathjax (1)</a></li><li><a href='/blog/categories/movie'>movie (1)</a></li><li><a href='/blog/categories/network'>network (5)</a></li><li><a href='/blog/categories/octopress'>octopress (8)</a></li><li><a href='/blog/categories/owncloud'>owncloud (1)</a></li><li><a href='/blog/categories/proxy'>proxy (5)</a></li><li><a href='/blog/categories/pthread'>pthread (2)</a></li><li><a href='/blog/categories/python'>python (1)</a></li><li><a href='/blog/categories/raspberrypi'>raspberrypi (8)</a></li><li><a href='/blog/categories/raspbian'>raspbian (1)</a></li><li><a href='/blog/categories/shadowsocks'>shadowsocks (1)</a></li><li><a href='/blog/categories/sns'>SNS (1)</a></li><li><a href='/blog/categories/society'>society (5)</a></li><li><a href='/blog/categories/software'>software (1)</a></li><li><a href='/blog/categories/ssh'>ssh (2)</a></li><li><a href='/blog/categories/stunnel'>stunnel (3)</a></li><li><a href='/blog/categories/tech'>tech (16)</a></li><li><a href='/blog/categories/test'>test (2)</a></li><li><a href='/blog/categories/transgene'>transgene (1)</a></li><li><a href='/blog/categories/twip'>twip (1)</a></li><li><a href='/blog/categories/twitter'>twitter (4)</a></li><li><a href='/blog/categories/vpn'>vpn (1)</a></li><li><a href='/blog/categories/wpad'>WPAD (1)</a></li></ul>
</section>

  
</aside>


    </div>
  </div>
  <footer role="contentinfo"><p>
  Copyright &copy; 2016 - xixitalk -
  <span class="credit">Powered by <a href="http://octopress.org">Octopress</a></span>
</p>

</footer>
  

<script type="text/javascript">
      var disqus_shortname = 'gitblog';
      
        
        // var disqus_developer = 1;
        var disqus_identifier = 'http://xixitalk.github.io/blog/2014/04/06/twitter-python-badstatusline/';
        var disqus_url = 'http://xixitalk.github.io/blog/2014/04/06/twitter-python-badstatusline/';
        var disqus_script = 'embed.js';
      
    (function () {
      var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
      dsq.src = 'http://' + disqus_shortname + '.disqus.com/' + disqus_script;
      (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
    }());
</script>











</body>
</html>
